---
title: "AM01 Final Project Group 4"
author: "Study Group 4 - Harsh Tripathi, Nikolaos Panayotou, Wei Guo, Xenia Huber, Xinyue Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r load-libraries, echo=FALSE}
library(googlesheets4)
library(tidyverse)
library(janitor) 
library(skimr)
library(countrycode) # to clean up country names
library(broom)
library(car)
library(ggfortify)
library(stringr)
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(tidyquant)
library(infer)
library(openintro)
```


```{r load_data}

#read local copy
ask_a_manager_2021 <- read_csv(here::here("data", "ask_a_manager_2021.csv")) %>% 
  janitor::clean_names()
  
#skim the data
skimr::skim(ask_a_manager_2021)
```


```{r, data_cleaning}
#data cleaning


ask_a_manager_2021_new <- ask_a_manager_2021 %>% 
  #rename long columns
  rename(age=how_old_are_you,overall_experience=overall_years_of_professional_experience,
         field_experience=years_of_experience_in_field,education_level=highest_level_of_education_completed) %>% 
  #remove certain columns
  select(-timestamp,
         -additional_context_on_job_title ,
         -additional_context_on_income,
         -other_monetary_comp,
         -currency_other) %>% 
  #mutate ordered factors
  mutate(age=factor(age,
                    levels=c("under 18","18-24","25-34","35-44","45-54","55-64","65 or over"),
                    labels =c("under 18","18-24","25-34","35-44","45-54","55-64","65 or over") ,
                    ordered = TRUE),
         
         overall_experience=factor(overall_experience,
                                   levels=c("1 year or less","2 - 4 years","5-7 years","8 - 10 years","11 - 20 years","21 - 30 years","31 - 40 years","41 years or more"),
                                   labels =c("less than 1 year","2-4 years","5-7 years","8-10 years","11-20 years","21-30 years","31-40 years","41 years or more") ,ordered = TRUE),
         
         field_experience=factor(field_experience,
                                 levels=c("1 year or less","2 - 4 years","5-7 years","8 - 10 years","11 - 20 years","21 - 30 years","31 - 40 years","41 years or more"),
                                 labels =c("less than 1 year","2-4 years","5-7 years","8-10 years","11-20 years","21-30 years","31-40 years","41 years or more") ,
                                 ordered = TRUE),
         education_level=factor(education_level,levels=c("High School","Some college","College degree","Master's degree","PhD","Professional degree (MD, JD, etc.)"),
                                labels =c("High School","Some college","College degree",
                                          "Master's degree","PhD","Professional degree"),
                                ordered = TRUE),
         gender=case_when(
           gender=="Other or prefer not to answer"|gender=="Prefer not to answer"|is.na(gender)~"Don't know or NA",
           TRUE~gender),state=ifelse(str_detect(state,",")|is.na(state),"NA",state))

#sort out country

# First we need to convert country name to iso3c
ask_a_manager_2021_new$iso3c <-countrycode(
  ask_a_manager_2021_new$country,
  origin = "country.name", destination = "iso3c")
# then change it back to country name
ask_a_manager_2021_new$country <-countrycode(
  ask_a_manager_2021_new$iso3c,
  origin = "iso3c", destination = "country.name")

#create a list of industries with more than 100 respondents
industry_list<-ask_a_manager_2021_new %>% 
        group_by(industry) %>% 
        count(sort=TRUE) %>% 
        filter(n > 100) %>% 
        select(industry) %>% pull()
#filter datafame so that it includes only those industries
ask_a_manager_2021_new<-ask_a_manager_2021_new %>% 
     filter(industry %in% industry_list)

#create a list of races with more than 100 respondents
race_list<-ask_a_manager_2021_new %>% 
  group_by(race) %>% 
  count(sort=TRUE) %>% 
  filter(!is.na(race),n>100) %>% 
  select(race) %>% pull()
ask_a_manager_2021_new<-ask_a_manager_2021_new %>% 
  filter(race %in% race_list)

```

```{r}
skim(ask_a_manager_2021_new)
```

```{r cleaned_data}
#drop_na
ask_a_manager_2021_cleaned<-
  ask_a_manager_2021_new %>%  drop_na()

#filter
ask_a_manager_2021_cleaned<-
  ask_a_manager_2021_cleaned %>% 
  filter(annual_salary>10000&annual_salary<1000000)

skim(ask_a_manager_2021_cleaned)
```

```{r, salary distribution}

# How is salary distributed?
ggplot(ask_a_manager_2021_cleaned, aes(y=annual_salary))+
  geom_boxplot()+
 labs(y="Annual Salary", 
       x="",
       title="Boxplot of Annual Salary")+
  theme_bw()+
   theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggplot(ask_a_manager_2021_cleaned, aes(x=annual_salary))+
  stat_ecdf()+
   labs(y="ECDF value", 
       x="Annual Salary",
       title="ECDF plot of Annual Salary")+
  theme_bw()
```


```{r, log salary distribution}

# what about log(salary)? 
ggplot(ask_a_manager_2021_cleaned, aes(x=log(annual_salary)))+
  geom_density()+
  labs(y="Density", 
       x="Log of Annual Salary",
       title="Density plot of log(Annual Salary)")+
  theme_bw()


ggplot(ask_a_manager_2021_cleaned, aes(x=log(annual_salary)))+
  stat_ecdf()+
  labs(y="ECDF value", 
       x="Log of Annual Salary",
       title="ECDF plot of log(Annual Salary)")+
  theme_bw()

# Which one (salary vs. log(salary)) is better to use in a regression model? Why?
#log salary appears to b more evenly distributed.
```



```{r, age distribution }
# age distribution in the survey

ask_a_manager_2021_cleaned %>% 
  count(age) %>% 
  ggplot(aes(x=age,y=n,fill=age)) +
  geom_col()+
  labs(x="Age group", 
       y="Count")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme_bw()+
  scale_fill_brewer(palette = "Blues")+
  guides(fill=FALSE)


```


```{r, most observed industries }
# More than 1000 industries can be observed in our dtaframe
#we will filter for industries with more than 500 respondents

ask_a_manager_2021_cleaned %>% 
  count(industry, sort=TRUE) %>% 
  mutate(percent = 100* n/sum(n)) %>% 
  filter(n>=500) %>% 
  ggplot(aes(x=fct_reorder(industry,n,.desc = TRUE),y= n,fill=industry))+
  geom_col(fill= "slateblue1")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
    labs(x="Industry", 
       y="Count",
       title="Industries with >500 repondents")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))+
  guides(fill=FALSE)
```


```{r, most observed currencies }
# Most of 'currency' is USD
ask_a_manager_2021_cleaned %>% 
  count(currency, sort=TRUE) %>% 
  mutate(percent = 100* n/sum(n)) %>% 
  #plot the counts of each currency
  ggplot(aes(x=fct_reorder(currency,n,.desc=TRUE),y= n,fill=currency))+
  geom_col(fill= "slateblue1")+
  labs(x="Currency Paid", 
       y="Count")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme_bw()+
  guides(fill=FALSE)

```


```{r, countries with the most respondents }
#we will filter for countries with the most respondents
ask_a_manager_2021_cleaned %>% 
  count(country, sort=TRUE) %>% 
  top_n(10) %>% 
#plot the counts of each country
  ggplot(aes(x=fct_reorder(country,n,.desc=TRUE),y= n,fill=country))+
  geom_col(fill= "slateblue1")+
  theme_bw()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  labs(y="Count", 
       x="Country")+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))+
  NULL
# use countrycode::countryname() to clean country names
```


```{r, city barchart }
# 'city' 
ask_a_manager_2021_cleaned %>% 
  count(city, sort=TRUE) %>% 
  # mutate(percent = 100* n/sum(n)) %>% 
  top_n(15) %>% 
  ggplot(aes(x=fct_reorder(city,n, .desc=TRUE),y= n))+
  geom_col(fill= "slateblue1")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme_bw()+
  labs(title="Frequencies of Cities",
       y="Count", 
       x="City")+
   guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))+
  NULL
```


```{r, education level bar chart }
# education
ask_a_manager_2021_cleaned %>% 
  filter(!is.na(education_level)) %>% 
  count(education_level) %>% 
  ggplot(aes(x=education_level,y= n,fill=education_level))+
  geom_col()+
  theme_bw()+
  labs(title= "Frequency of each educational level",
       x= "Education level",
       y="Count")+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r, observe the frequencies of each gender}
# gender
ask_a_manager_2021_cleaned %>% 
  #remove null or other responses
  filter(gender %in% c("Woman","Man","Non-binary")) %>% 
  count(gender) %>% 
  ggplot(aes(x=fct_reorder(gender,n,.desc=TRUE),y = n,fill=gender))+
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  labs(title= "Frequency of each gender",
       x="Gender",
       y="Count")+
  NULL
```


```{r, race variable manipulation}

#Cleaning the race variable(white was included with other races)
ask_a_manager_2021_cleaned <- ask_a_manager_2021_cleaned %>% 
  mutate(
    race_cleaned = case_when(
      race %in% c('Asian or Asian American', 'Asian or Asian American, White') ~ 'Asian or Asian American',
      race %in% c('Black or African American', 'Black or African American, White') ~ 'Black or African American',
      race %in% c('Hispanic, Latino, or Spanish origin', 'Hispanic, Latino, or Spanish origin, White') ~ 'Hispanic, Latino, or Spanish origin',
      race == "Another option not listed here or prefer not to answer" ~ "Others/Prefer not to say",
      TRUE ~ race
    )
  )
skim(ask_a_manager_2021_cleaned$race_cleaned)
```


```{r, plot the race frequencies }
# race
ask_a_manager_2021_cleaned %>% 
  filter(!is.na(race_cleaned)) %>% 
  count(race_cleaned) %>% 
  ggplot(aes(x=fct_reorder(race_cleaned,n,.desc=TRUE),y= n,fill=race_cleaned))+
  geom_col(fill= "slateblue1")+
  theme_bw()+
  labs(title="Race Frequency",
       x= "Race",
       y="Count")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r, varchart for proffesional experience years }

# overall_years_of_professional_experience 
ask_a_manager_2021_cleaned %>% 
  count(overall_experience ) %>% 
  ggplot(aes(x=overall_experience,y = n))+
  geom_col(fill= "slateblue1")+
  labs(x="Years of Professional Experience", 
       y="Count",
       title="Years of Experience Frequency")+
  theme_bw()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```


```{r, barchart for years of professional experience in particular field }
# years_of_experience_in_field  
ask_a_manager_2021_cleaned %>% 
  count(field_experience) %>% 
  ggplot(aes(x=field_experience,y = n))+
  geom_col(fill= "slateblue1")+
   labs(x="Years of Experience in Particular Field", 
       y="Count",
       title="Frequency of Field Experience")+
  theme_bw()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))

```
After viewing the data distribution in survey level, let's dig into salary in US.

```{r}
#delete country and rename country value as iso3, filter USA
us_data <-
  ask_a_manager_2021_cleaned %>% 
  select(-country) %>% 
  filter(iso3c== "USA")

us_data <- us_data %>%
  mutate(
    log_salary = log(annual_salary)
    ) %>% 
  drop_na()
```



```{r, salaries acros USA cities}
#create a table with mean salaries across different US cities
us_data %>% 
  group_by(city) %>% 
  summarise(mean_salary = mean(annual_salary),
            count = n()
         ) %>% 
  arrange(desc(count)) %>% 
  #display only top 15
 top_n(15) 
```


```{r, SF hypothesis}

#we will examine if San francisco holds a bigger proportion of tech employees than other cities


#find % of tech employees in SF
us_data %>% 
  filter(city == "San Francisco") %>% 
  count(industry) %>% 
  mutate(percent = n/sum(n)*100,
         total = sum(n)) %>%  
  arrange(desc(n))
#find % of tech employees in US excluding SF  
us_data %>% 
  filter(city != "San Francisco") %>% 
  count(industry) %>% 
  mutate(percent = n/sum(n)*100,
         total = sum(n)) %>% 
  arrange(desc(n))


#two proportion z test
tech<- c(243, 3174)
totals <- c(504, 18990	)

res1 <- prop.test(x = tech, n = totals)
res1

```
```{r, gender frequencies}

us_data %>%
  filter(gender %in% c("Woman","Man","Non-binary")) %>% 
  count(gender) %>% 
  ggplot(aes(x=fct_reorder(gender,n,.desc=TRUE),y = n,fill=gender))+
  geom_col()+
  theme_bw()+
  scale_fill_brewer(palette = "Blues")+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  guides(fill=FALSE)+
  labs(x="Gender",y="Count")+
  NULL

```

```{r,compare salaries fo each gender, fig.width=12}

#create table
us_data %>% 
  group_by(gender) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
#plot barchart  
  ggplot(aes(x = reorder(gender, -mean_salary), y = mean_salary)) +
  geom_col(fill= "slateblue1")+
 # geom_text(aes(label=mean_salary),size=3,vjust=-0.25)+
   labs(x="Gender", 
       y="Average Salary",
       title="Average Salary for Gender (US)")+
  theme_bw()
```


```{r, facet wrap for women and men}

#display unique gender values
unique(us_data["gender"])

us_data %>% 
  group_by(gender) %>% 
  count(industry, sort=TRUE) %>% 
  mutate(percent = 100* n/sum(n)) %>% 
  filter(n>=500) %>% 
  ggplot(aes(y=fct_reorder(industry,n,.desc = TRUE),x= n,fill=industry))+
  geom_col()+
  geom_text(aes(label=n),size=3,vjust=-0.25)+
  facet_wrap(~gender)+
    labs(x="Industry", 
      y="Count",
       title="Industries with >500 repondents",
      subtitle="Men only work in the tech industy for our data")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))+
  guides(fill=FALSE)
```


CHANGE THIS
Null Hypothesis $H_0$ : $\mu_{Men.tech.salary} - \mu_{Female.tech.salary} = 0$

Alternative Hypothesis $H_1$ : $\mu_{Men.tech.salary} - \mu_{Female.tech.salary}\neq 0$
```{r, Salaries in Tech for each gender, height = 0.1}

#compute confidence intervals

us_data_menvswomen <- us_data%>%
  filter(industry == "Computing or Tech") %>% 
  filter(gender %in% c("Man", "Woman")) %>% 
  group_by(gender) %>% 
  summarise(mean_salary = mean(annual_salary),
            median_salary = median(annual_salary),
            sd_salary = sd(annual_salary),
            count = n(),
            # get t-critical value with (n-1) degrees of freedom
            t_critical = qt(0.975, count-1),
            se_salary = sd_salary/sqrt(count),
            margin_of_error = t_critical * se_salary,
            salary_low = mean_salary - margin_of_error,
            salary_high = mean_salary + margin_of_error) %>% 
  arrange(desc(mean_salary))
  us_data_menvswomen
  
 # using welch  t test
us_data_2 <- us_data %>% 
    filter(industry == "Computing or Tech") %>% 
  filter(gender %in% c("Man", "Woman"))
us_data_2

t.test(annual_salary ~ gender , data = us_data_2)

#boxplots
us_data %>% 
  group_by(gender) %>% 
  ggplot(aes(x=gender, y=annual_salary))+
  geom_boxplot()+
  labs(x="Gender", 
       y="Annual Salary",
       title="Annual Salary for Gender (US)")+
  theme_bw()

us_data %>% 
  filter(industry == "Computing or Tech") %>% 
  group_by(gender) %>% 
  ggplot(aes(x=gender, y=annual_salary))+
  geom_boxplot()+
   labs(x="Gender", 
       y="Annual Salary in Tech",
       title="Annual Salary in Tech for Gender (US)")+
  theme_bw()
```



```{r, asians in tech}
#plot race in tech industry


us_data %>% 
  filter(industry == "Computing or Tech", race_cleaned != "Others/Prefer not to say") %>%
  group_by(race_cleaned) %>% 
  summarize(
   count = n()
   ) %>% 
  
  ggplot(aes(x = reorder(race_cleaned, -count), y = count)) +
  geom_col(fill= "slateblue1") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))+
   labs(x="Race", 
       y="Frequency",
       title="Frequency of each race in Tech")+
  theme_bw()+
  geom_text(aes(label=count),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))



```
NEEDS FIXING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
```{r, proportion of asians in tech vs in other idustries}
# #race proportions for tech 
#  us_data %>% 
#   filter(industry == "Computing or Tech") %>% 
#   count(race_cleaned) %>% 
#   mutate(percent = n/sum(n)*100)
#   
# #race proportions for non tech industries
# 
# us_data %>% 
#   filter(industry != "Computing or Tech") %>% 
#   count(race_cleaned) %>% 
#   mutate(percent = n/sum(n)*100)

#calculate proportions

us_data%>%
  mutate(tech_or_not = case_when(industry == "Computing or Tech"& race_cleaned=="Asian or Asian American" ~ "asian in tech",
                                 industry == "Computing or Tech"& race_cleaned!="Asian or Asian American" ~ "other in tech",
                                 industry != "Computing or Tech"& race_cleaned=="Asian or Asian American" ~ "asian in other industyr",
                                 industry != "Computing or Tech"& race_cleaned!="Asian or Asian American" ~ "other in other industry")
  ) %>% 
  count(tech_or_not) 
  # mutate(proportion = n/sum(n),
  #        s_e = sqrt(proportion*(1-proportion)/sum(n)),
  #        t_critical = qt(0.975,n-1),
  #        interval_low = proportion - s_e*t_critical,
  #        interval_high = proportion + s_e*t_critical
  #        ) 
#two proportion z test
asians<- c(321, 865)
totals <- c(321+3096, 865 + 15212)

res <- prop.test(x = asians, n = totals)
res


```


```{r, fig.width=12}
us_data %>% 
  group_by(race_cleaned) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = reorder(race_cleaned, -mean_salary), y = mean_salary)) +
  geom_col(fill= "slateblue1") +
  labs(x="Race", 
       y="Average Salary",
       title="Average salary for every race")+
  theme_bw()+
  geom_text(aes(label=mean_salary),size=3,vjust=-0.25)+
  theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
```
****(maybe hyporthesis testing between races)****

```{r, t test between salaries for different races}

us_data%>%
  group_by(race_cleaned) %>% 
  summarise(mean_salary = mean(annual_salary),
            median_salary = median(annual_salary),
            sd_salary = sd(annual_salary),
            count = n(),
            # get t-critical value with (n-1) degrees of freedom
            t_critical = qt(0.975, count-1),
            se_salary = sd_salary/sqrt(count),
            margin_of_error = t_critical * se_salary,
            salary_low = mean_salary - margin_of_error,
            salary_high = mean_salary + margin_of_error) %>% 
  arrange(desc(mean_salary))

 # using welch  t test
us_data_race <- us_data %>% 
  filter(race_cleaned %in% c("White", "Asian or Asian American"))

t.test(annual_salary ~ race_cleaned , data = us_data_race) 



```


```{r,mean salaries for diferent industries fig.width=12}

top_industries <- us_data %>% 
  group_by(industry) %>% 
  count(sort = TRUE) %>% 
  head(10) %>% 
  select(industry) %>% 
  pull()

us_data %>%
  filter(industry %in% top_industries) %>% 
  group_by(industry) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  ggplot(aes(x = reorder(industry, -mean_salary), y = mean_salary)) +
  geom_col(fill= "slateblue1") +
   labs(x="Industry", 
       y="Average Salary",
       title="Average salary for every industry")+
  theme_bw()+
 theme(axis.text.x = element_text(angle = 45, vjust = 0.5))


us_data %>%
  filter(industry %in% top_industries) %>% 
  group_by(industry) %>% 
  ggplot(aes(x = reorder(industry, -annual_salary), y = annual_salary)) +
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs(x="Industry", 
       y="Average Salary",
       title="Distribution of salary for every industry")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))+
  NULL
```


```{r,salary vs experience levels, fig.width = 12}

us_data %>%
  group_by(overall_experience) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = overall_experience, y = mean_salary)) +
  geom_col(fill= "slateblue1")+
   labs(x="Overall Experience", 
       y="Average Salary",
       title="Average salary for different experience levels")+
  theme_bw()+
  NULL
```
```{r}
#MAYBE TAKE A LOOK LATER
# #corelation between exp and salary
# library(moderndive)
# #cor.test(overall_experience ~ mean_salary)
# us_data %>% 
# get_correlation(annual_salary~overall_experience)
# 

```

```{r, average salary vs age,fig.width = 12}
us_data %>%
  group_by(age) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = age, y = mean_salary)) +
  geom_col(fill= "slateblue1")+
  labs(x="Age", 
       y="Average Salary",
       title="Barchart of average salary for age")+
  theme_bw()+
  NULL


us_data %>%
  group_by(age) %>% 
  
  ggplot(aes(x = age, y = annual_salary)) +
   geom_violin()+
  geom_boxplot(width=0.1)+
   labs(x="Age", 
       y="Annual Salary",
       title="Distribution of annual salary for age")+
  theme_bw()+
  NULL
 
#INCLUDE CONFIDENCE INTERVALs!!!!!!!!!!!!!!!


```


```{r, fig.width = 12}
us_data %>%
  group_by(field_experience) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = field_experience, y = mean_salary)) +
  geom_col(fill= "slateblue1")+
  labs(x="Field Experience", 
       y="Average Salary",
       title="Average salary for different fiel experience")+
  theme_bw()+
  NULL
```


```{r, fig.width = 12}
us_data %>%
  group_by(education_level) %>% 
  summarize(
    mean_salary = mean(annual_salary)
  ) %>% 
  
  ggplot(aes(x = education_level, y = mean_salary)) +
  geom_col(fill= "slateblue1")+
  labs(x="Education Level", 
       y="Average Salary",
       title="Average salary for different education levels")+
  theme_bw()+
  NULL


us_data %>%
 group_by(race_cleaned) %>% 
  #count(education_level)
  mutate(
    n= count(education_level),
    proportion = n/sum(n)
  ) %>% 
  
  ggplot(aes(x = education_level, y = proportion)) +
  geom_col(fill= "slateblue1")+
  facet_wrap(~race_cleaned)+
  labs(x="education level", 
       y="proportion",
       title="proportions of different education levels")+
  theme_bw()+
  NULL
```
